name: 'Action'
description: 'Description'
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Run a one-line script
      shell: bash
      run: echo Hello, world!
    - name: Run a multi-line script
      shell: bash
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: Python version
      shell: bash
      run: python --version