name: Deployment Workflow

on:
  push:
  workflow_dispatch:

jobs:
  job1:
    name: Job 1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
  job2:
    name: Job 2
    needs: job1
    uses: ./.github/workflows/reusable-workflow.yaml
    with:
      system: 'linux'

  job3:
    name: Job 3
    runs-on: ubuntu-latest
    needs: job2
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Action
        uses: kemal-gokhan/githubactions/.github/actions/folder1/action.yml@main
      - name: Normal Step
        run: echo "Bu normal bir step."
      - name: Action
        uses: kemal-gokhan/githubactions/.github/actions/folder1/action.yml@main
        
