name: Issue Comment Checker

on:
  issue_comment:
    types: [created]

jobs:
  issue_commented:
    # This job only runs for issue comments
    name: Issue comment
    if: ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Issue number: ${{ github.event.issue.number }}"
          echo "Comment author: ${{ github.event.comment.user.login }}"
          echo "Comment: ${{ github.event.comment.body }}"
          echo "Comment ID: ${{ github.event.comment.id }}"
      - shell: bash
        run: |
          if [[ "${{ github.event.comment.body }}" == "approve" && "${{ github.event.comment.user.login }}" =~ ^(kemal-gokhan)$ ]]; then
            echo "Approved by ${{ github.event.comment.user.login }}"
          else
            echo "Not approved because the comment is not 'approve' or the comment author is not privileged user"
          fi
          