name: Push for testing

on:
  push:

jobs:
  j1:
    runs-on: [ubuntu-latest]
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Git tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "HOME=$HOME" >> $GITHUB_ENV
          git config --global user.name "Kemal"
          git config --global user.email "ops@kemal.com"
          TAG="v.${{ github.head_ref || github.ref_name }}.$GITHUB_RUN_NUMBER"
          git tag -a $TAG -m "[GithubAction CI] New Tag"
          git push origin ${{ github.head_ref || github.ref_name }} $TAG
  j2:
    runs-on: [ubuntu-latest]
    needs: j1
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v4
      - shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh issue create --assignee ${{ vars.DEPLOYMENT_APPROVERS }} --title "${{ github.head_ref || github.ref_name }} needs approval | ${{ github.actor }} | ${{ github.run_id }}" \
          --body "sourcebranch: preview-deploy system: preview created by ${{ github.actor }}. It needs approval from the assignees in order to deploy."

          