name: Reusable Workflow

on:
  workflow_call:
    inputs:
      system:
        description: 'Name of the systme'
        required: true
        type: string

jobs:
  is1:
    runs-on: ubuntu-latest
    steps:
      - name: Print1
        run: echo "Hello, my system is ${{ inputs.system }}"
  is2:
    runs-on: ubuntu-latest
    steps:
      - name: Print2
        run: echo "Hello from is2"